### ISSUE TITLE
Missing orchestration.py in 'main' branch

### ISSUE THREAD

**Issue by noorains** [prio-data/views_pipeline#18]
## Description
orchestration.py file is missing in 'main' branch, I pulled the main branch to run all the models together with baseline but couldn't find the script in the 'main' branch.

## Steps to Reproduce
<img width="845" alt="image" src="https://github.com/prio-data/views_pipeline/assets/142994595/a1aff075-3743-493a-986c-8d6670be895c">

## Expected Behavior
<img width="848" alt="image" src="https://github.com/prio-data/views_pipeline/assets/142994595/e5826564-f155-415b-90fa-24f66074ad42">

## Actual Behavior

orchestration.py file is missing

## Screenshots
<img width="921" alt="image" src="https://github.com/prio-data/views_pipeline/assets/142994595/b19b2fc3-4193-426a-9554-4834d86be1b9">

**Comment by sarakallis** [comment]
It's in the production models branch. We are aware!

**Comment by noorains** [comment]
Thanks. It is mentioned in the readme of the 'main' branch so it would be great if it is made available here in 'main' so that the pipeline is fully executable through 'main'. I also want to execute baseline models using the orchestration.py script when I pull from 'main' since it is our 'main' production branch and we are pulling from it. The production_model branch was last updated 2 months ago and its documentation is not updated. 

<img width="924" alt="image" src="https://github.com/prio-data/views_pipeline/assets/142994595/90b20c23-4058-4717-af15-1a83ec85367e">
