### ISSUE TITLE
 Check and Update `meta_tools/make_new_model_dir.py` Script

### ISSUE THREAD

**Issue by Polichinel** [prio-data/views_pipeline#65]
# Objective
Ensure that the `meta_tools/make_new_model_dir.py` script is up-to-date and aligned with the latest sub-model directory structure in the main branch.

# Requirements:

- **Directory Structure**: 
  - Verify that the script creates sub-model directories according to the latest structure found in the main branch.
  
- **Future Flexibility**: 
  - Ensure the script can accommodate future functionality for generating boilerplate code, such as config files, main files, and management scripts.

- **Directory Assessment**: 
  - After updating the `make_new_model_dir.py` script, ensure the `meta_tools/assess_model_dir.py` script is updated accordingly to validate the newly created directories.

# Additional Features:

- **Branch**: Work on a new branch named `update_make_model_dir_01`.

- **README Generation**: 
  - The script should generate a basic README file in each sub-model directory, including metadata such as the time the directory was created.

- **Error Handling & Logging**: 
  - Improve error handling and logging where necessary to ensure robustness.

---

### Actionable Steps:
- [x] **Check the current directory structure** in the main branch and ensure the script creates directories that align with it.
- [x] **Prepare for future updates** by making the script flexible enough to accommodate boilerplate code generation for configs, main files, and management.
- [x] **Update and run `assess_model_dir.py`** to validate the newly generated directories.
- [x] **Check out the branch `update_make_model_dir_01`** for this task.
- [x] **Ensure the script generates a README** in each directory with basic metadata (e.g., creation time).
- [x] Improve **error handling and logging** if needed.

---

This provides a clear, structured approach for updating and verifying the script. Let me know if any adjustments are needed!

**Comment by smellycloud** [comment]
- assess_model_dir.py functionality has been merged into ModelScriptBuilder and ModelDirectoryBuilder for each case respectively as each have their own structural requirements. Assessment done by calling assess() after build() in both cases.
