### ISSUE TITLE
Create Function for Generating Configuration Files

### ISSUE THREAD

**Issue by Polichinel** [prio-data/views_pipeline#66]
# Objective
Develop a function to generate the five configuration files for each model, with a wrapper function to handle the process across all configs.

NOTE: first solve:
- https://github.com/prio-data/views_pipeline/issues/65

# Requirements:

- **Functions**:
  - Create **five individual functions**, one for each type of configuration file.
  - Implement a **wrapper function** that can call these five functions to generate all configs at once.

- **Templates**:
  - If necessary, create a directory under `views_pipeline/meta_tools/` called `templates` to store boilerplate templates for the configuration files.

- **Default Values**:
  - In `config_deployment.py`, set the default value for `"deployment_status"` to `"shadow"` (with options: shadow, deployed, baseline, deprecated).
  - Use the model-specific subdirectory name in `config_meta.py` under `"name"`.
  - If other fields could benefit from default values or need to be set during the creation of configs, implement those as needed.

- **Flexibility**:
  - The function should be flexible enough to accommodate various model types.

- **File Location**:
  - Save the generated configuration files in the `model/configs` directory.

- **Validation**:
  - A separate test in `meta_tools` should be created to validate the generated configuration files.
  - This validation test should run automatically after the config generation script.

- **Naming & Format**:
  - Follow the naming conventions and formats specified in the relevant ADR (see link).

---

# Actionable Steps:
- [x] Create five functions for generating the individual config files.
- [x]  Implement a wrapper function to generate all config files for a given model.
- [x] Store templates for the config files in `views_pipeline/meta_tools/templates` if necessary.
- [x]  Set default values for `"deployment_status"` in `config_deployment.py` and `"name"` in `config_meta.py`.
- [x]  Ensure the function is flexible enough to accommodate different model types.
- [x]  Save the config files in the `model/configs` directory.
- [x]  Implement a separate validation test to check the generated config files, and ensure it runs automatically after the script.
- [x]  Follow the ADR guidelines for naming conventions and formatting.

**Comment by smellycloud** [comment]
- Added a model_naming.py file in meta_tools/utils to force basic adjective_noun naming convention.
- Refactored directory and script building+assessment into their own classes. Execution behavior and outputs are the same.
- Created templates and builder functions for main.py and get_data.py if necessary. Not active.

**Comment by smellycloud** [comment]
- Closed pull request to refactor script templates into separate files within a templates directory for better readability.
- Created meta_tools/utils/utils_script_gen.py to handle saving script files at specified locations.
- Clarified docstrings in all template files.
- TODO: rename model_naming.py to utils_model_naming.py and refactor to be consistent with naming scheme in common_utils.
